# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sam-python312-template"

[default.build.parameters]
cached = true
parallel = true
template = "./template.yaml"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"


[local]
[local.global.parameters]
stack_name = "local-sam-python312-template"
parameter_overrides = [
    "Stage=local",
    "ApiVersionHash=latest",
    "ApiCorsAllowedOrigins=http://localhost:3000,http://localhost:3005",
]

[local.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
region = "ap-northeast-1"
s3_bucket = "local-sam-python312-template-deployment-bucket"
tags = ["STAGE=local"]

[local.local_start_api.parameters]
warm_containers = "EAGER"

[local.local_start_lambda.parameters]
warm_containers = "EAGER"

[local.sync.parameters]
watch = false


[dev]
[dev.global.parameters]
stack_name = "dev-sam-python312-template"
parameter_overrides = [
    "Stage=dev",
    "ApiVersionHash=latest",
    "ApiCorsAllowedOrigins=http://localhost:3000,http://localhost:3005",
]

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
region = "ap-northeast-1"
s3_bucket = "dev-sam-python312-template-deployment-bucket"
tags = ["STAGE=dev"]
