name: Python Dependencies Vulnerability Check

# pyproject.tomlが変更されたときに実行
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "pyproject.toml"

jobs:
  dependencies-vulnerability-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Install dependencies
        uses: ./.github/actions/install-pip-dependencies

      - name: Install Safety
        run: pip install safety

      - name: Export requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt

      - name: Run safety check
        run: safety check -r requirements.txt
